supermerill/SuperSlicer

src/slic3r/GUI/GLCanvas3D.cpp
Without this it is not possible to add/remove details when z_step is greater than 0.01 because strength is set to 0.005 which cause ignoring it.
p.s. 
Sorry for doubling pull request
=> Fix manual editing variable layer height

resources/ui_layout/print.ui, src/libslic3r/Layer.cpp, src/libslic3r/PerimeterGenerator.cpp, src/libslic3r/PrintConfig.cpp, src/libslic3r/PrintConfig.hpp, src/slic3r/GUI/ConfigManipulation.cpp, src/slic3r/GUI/Preset.cpp
In general we don't like overlapping perimeters, but occasionally it is useful to allow the outermost perimeter to overlap, so that we have one continuous extrusion around the part, improving edge quality and layer adhesion. This PR adds an "overlapping perimeters count" option, to allow only the outermost *n* perimeters to overlap themselves.
Motivating example
----
([STL here](https://github.com/VoronDesign/Voron-0/blob/7ef301b8c9762fcdea52bcf256fc1fd6d5d09232/VORON-0/STLs/VORON0.0/Dragon_Toolhead/Toolhead_Right_Dragon_x1.STL), 0.2 layers, 0.44 extrusion widths, 4 perimeters, first layer):
The lower left part has "overlapping perimeters" enabled (for all perimeters). This results in a single thick line in the circled area disconnected from the rest of the part (despite having …
=> Add option to limit the number of overlapping perimeters

src/libslic3r/GCode/WipeTower.cpp
Had a build failure due to a missing declaration for boost::algorithm::to_upper_copy
=> Add missing header for boost::algorithm::to_upper_copy

src/libslic3r/GCode.cpp
so that changes made for the extrusion role can be undone when the
extrusion role changes again.
=> Added "last_extrusion_role" placeholder for extrusion role changes

resources/profiles/Creality.ini
Fix typo so that configuration name (=print:0.08mm HIGHDETAIL @CREALITY) matches configuration (layer_height = 0.08)
=> Fix typo in Creality.ini

.github/workflows/ccpp_mac.yml, .github/workflows/ccpp_ubuntu.yml, .github/workflows/ccpp_win.yml
* good for making build-success a requirement before merging to master
* enable the following _after_ this is merged
=> build all pull requests

.gitignore
These files don't need to be kept under configuration management. And when cloning a project on a Mac, they will be created very quickly.
=> Ignore DS_Store files in MacOS

resources/ui_layout/print.ui, src/libslic3r/GCode.cpp, src/libslic3r/GCodeWriter.cpp, src/libslic3r/Preset.cpp, src/libslic3r/Print.cpp, src/libslic3r/PrintConfig.cpp, src/libslic3r/PrintConfig.hpp
Addresses https://github.com/supermerill/SuperSlicer/issues/1154
=> WIP Added travel_speed_z.

src/libslic3r/PrintConfig.cpp
Made numerous minor corrections or improvements to spelling and grammar in print settings tooltips
However, I have not yet compiled this to test it. Nor have I changed the associated localization files.
=> Spelling and grammar in tooltips

src/libslic3r/PrintConfig.cpp
200% is really slow for Voron users running ERCF, we'd like to increase significantly.
=> Increase max wipe speed for Voron ERCF wipe towers

README.md
Right now, discord shield points to a non-functional link. This makes it easier to find a working one
=> README: point discord link to a particular comment

src/slic3r/GUI/CalibrationRetractionDialog.cpp
Dropdown entry shows "3x50°", but the temperature varies by a more usable 5°.
=> Typo in Retract Calibration for 3x5°

doc/How to build - Windows.md
further details on building on Windows 10. 
Before I did run into "Slic3r.dll was not loaded, error code: 193" although I took the latest libgmp-10.dll/ libmpfr-4.dll from the minGW distribution. Then I noticed, that these 2 dlls are shipped during the build process into "deps\build\destdir\usr\local\bin"
=> Update How to build - Windows.md

BuildMacOS.sh
i'm not sure if this pull request ist against the correct branch, but this fixes the currently failing MacOS builds.
i tested on my fork: https://github.com/mneuhaus/SuperSlicer/actions
=> Fix for failing MacOS builds because of zstd

src/libslic3r/GCode/WipeTower.cpp
A small bug was introduced when merging the changes made for: https://github.com/supermerill/SuperSlicer/issues/2611. The wait should be a requirement (so wait && (MarlinLegacy || Marlin)) which is not the case right now. This allows for a command like M104 R[temp] to go through when using Marlin flavor (non legacy) which doesn't  exist.
=> Tool change temp bugfix

cmake/modules/FindTBB.cmake.in
I thought I had included this earlier, but it seems to be missing.
OneTBB has the version info in a different file than the obsolete TBB.
=> Fix reading TBB version

src/slic3r/GUI/Search.cpp
The slicer often (every time?) crashes when doing material diff, as get_group_and_category can returns a stack variable as a reference.
This fixes it by returning a static ref when the config can't be found.
=> Fix for return of stack reference.

src/slic3r/GUI/UpdateDialogs.cpp
Nothing Fancy here
I was annoyed that the download link didn't work
=> Fixed Download Link of Slicer in the Update Message

src/libslic3r/PrintObject.cpp
The behavior of atomic_int64_t's default constructor will leave it to an uninitialized state (accessing it will be undefined behavior).
Use 0 to explicitly initialize it because it will be soon compared and exchanged.
=> fill_aligned_z: fix uninitialized atomic_int64_t

src/CMakeLists.txt
Currently the symlink target is hardcoded as slic3r, which is not the binary name of SuperSlicer.
Change it to use the variable for application command name instead.
=> fix Linux installation creating broken superslicer-gcodeviewer symlink
